name: Run Bot

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1) Repo එක checkout කරගන්නවා
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2) Node.js setup කරනවා
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3) Packages install කරනවා
      - name: Install Dependencies
        run: npm install

      # 4) Bot start කරනවා
      - name: Start Bot
        run: npm run start
